/**
 * API Registry — static catalog of all APIs available through Daemon.
 * Used for the settings dashboard, credits billing, and "what's included" showcase.
 */

export interface ApiService {
  id: string
  name: string
  provider: string
  category: 'ai' | 'search' | 'data' | 'comms' | 'travel' | 'social' | 'infra' | 'media'
  description: string
  costModel: string
  costPerUnit: number
  unit: string
  includedInFree: boolean
  includedInPro: boolean
  envKey: string
  status: 'active' | 'test' | 'inactive'
  docsUrl?: string
  emoji?: string
}

export const API_REGISTRY: ApiService[] = [
  // ── AI / LLM ─────────────────────────────────────────────
  {
    id: 'anthropic',
    name: 'Claude (Anthropic)',
    provider: 'Anthropic',
    category: 'ai',
    description: 'Best-in-class reasoning and code generation. Sonnet and Opus models.',
    costModel: '$3-75/M tokens (by model)',
    costPerUnit: 3.00,
    unit: 'M tokens',
    includedInFree: false,
    includedInPro: true,
    envKey: 'ANTHROPIC_API_KEY',
    status: 'active',
    docsUrl: 'https://docs.anthropic.com',
    emoji: '🧠',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    provider: 'OpenRouter',
    category: 'ai',
    description: 'Routes to any LLM. Pass-through pricing for 200+ models.',
    costModel: 'Pass-through pricing',
    costPerUnit: 0,
    unit: 'M tokens',
    includedInFree: true,
    includedInPro: true,
    envKey: 'OPENROUTER_API_KEY',
    status: 'active',
    docsUrl: 'https://openrouter.ai/docs',
    emoji: '🔀',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    provider: 'DeepSeek',
    category: 'ai',
    description: 'Cost-effective code model. Great for sub-agent coding tasks.',
    costModel: '$0.14-0.28/M tokens',
    costPerUnit: 0.14,
    unit: 'M tokens',
    includedInFree: false,
    includedInPro: true,
    envKey: 'DEEPSEEK_API_KEY',
    status: 'active',
    docsUrl: 'https://platform.deepseek.com/docs',
    emoji: '🐋',
  },
  {
    id: 'google-gemini',
    name: 'Google Gemini',
    provider: 'Google',
    category: 'ai',
    description: 'Multimodal AI. Flash for speed, Pro for reasoning. Multiple project keys.',
    costModel: '$0.075-1.25/M tokens',
    costPerUnit: 0.075,
    unit: 'M tokens',
    includedInFree: false,
    includedInPro: true,
    envKey: 'GOOGLE_API_KEY',
    status: 'active',
    docsUrl: 'https://ai.google.dev/docs',
    emoji: '💎',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    provider: 'OpenAI',
    category: 'ai',
    description: 'GPT-4o, o3, and more. Good all-rounder.',
    costModel: '$0.15-60/M tokens',
    costPerUnit: 0.15,
    unit: 'M tokens',
    includedInFree: false,
    includedInPro: true,
    envKey: 'OPENAI_API_KEY',
    status: 'active',
    docsUrl: 'https://platform.openai.com/docs',
    emoji: '🤖',
  },
  {
    id: 'deepgram',
    name: 'Deepgram',
    provider: 'Deepgram',
    category: 'ai',
    description: 'Speech-to-text. Fast, accurate transcription and real-time streaming.',
    costModel: '$0.0043/min',
    costPerUnit: 0.0043,
    unit: 'minute',
    includedInFree: false,
    includedInPro: true,
    envKey: 'DEEPGRAM_API_KEY',
    status: 'active',
    docsUrl: 'https://developers.deepgram.com',
    emoji: '🎙️',
  },

  // ── Search / Enrichment ──────────────────────────────────
  {
    id: 'brave-search',
    name: 'Brave Search',
    provider: 'Brave',
    category: 'search',
    description: 'Web search API. Privacy-focused, no tracking.',
    costModel: '$0.005/search',
    costPerUnit: 0.005,
    unit: 'search',
    includedInFree: false,
    includedInPro: true,
    envKey: 'BRAVE_SEARCH_API_KEY',
    status: 'active',
    docsUrl: 'https://brave.com/search/api/',
    emoji: '🔍',
  },
  {
    id: 'serpapi',
    name: 'SerpAPI',
    provider: 'SerpAPI',
    category: 'search',
    description: 'Google search results API. Structured SERP data.',
    costModel: '$0.01/search',
    costPerUnit: 0.01,
    unit: 'search',
    includedInFree: false,
    includedInPro: true,
    envKey: 'SERPAPI_KEY',
    status: 'active',
    docsUrl: 'https://serpapi.com/docs',
    emoji: '🌐',
  },
  {
    id: 'apollo',
    name: 'Apollo',
    provider: 'Apollo.io',
    category: 'search',
    description: 'Contact and company enrichment. Find emails, titles, company data.',
    costModel: '$0.01/contact',
    costPerUnit: 0.01,
    unit: 'contact',
    includedInFree: false,
    includedInPro: true,
    envKey: 'APOLLO_API_KEY',
    status: 'active',
    docsUrl: 'https://apolloio.github.io/apollo-api-docs/',
    emoji: '👤',
  },
  {
    id: 'dropcontact',
    name: 'Dropcontact',
    provider: 'Dropcontact',
    category: 'search',
    description: 'Email enrichment and verification. GDPR compliant.',
    costModel: '$0.05/contact',
    costPerUnit: 0.05,
    unit: 'contact',
    includedInFree: false,
    includedInPro: true,
    envKey: 'DROPCONTACT_API_KEY',
    status: 'active',
    docsUrl: 'https://developer.dropcontact.com',
    emoji: '📧',
  },

  // ── Data ─────────────────────────────────────────────────
  {
    id: 'qdrant',
    name: 'Qdrant Cloud',
    provider: 'Qdrant',
    category: 'data',
    description: 'Vector database. Semantic search, embeddings, memory.',
    costModel: 'Included',
    costPerUnit: 0,
    unit: 'query',
    includedInFree: true,
    includedInPro: true,
    envKey: 'QDRANT_API_KEY',
    status: 'active',
    docsUrl: 'https://qdrant.tech/documentation/',
    emoji: '🗄️',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    provider: 'HubSpot',
    category: 'data',
    description: 'CRM platform. Contact management, deals, pipelines.',
    costModel: 'Included',
    costPerUnit: 0,
    unit: 'request',
    includedInFree: false,
    includedInPro: true,
    envKey: 'HUBSPOT_API_KEY',
    status: 'active',
    docsUrl: 'https://developers.hubspot.com/docs',
    emoji: '📊',
  },
  {
    id: 'podio',
    name: 'Podio',
    provider: 'Citrix',
    category: 'data',
    description: 'Workspace CRM. Contacts, projects, workflows.',
    costModel: 'Included',
    costPerUnit: 0,
    unit: 'request',
    includedInFree: false,
    includedInPro: true,
    envKey: 'PODIO_CLIENT_ID',
    status: 'active',
    docsUrl: 'https://developers.podio.com',
    emoji: '📋',
  },
  {
    id: 'composio',
    name: 'Composio',
    provider: 'Composio',
    category: 'data',
    description: '500+ app integrations. Connect to Slack, Notion, Gmail, and more.',
    costModel: 'Included',
    costPerUnit: 0,
    unit: 'action',
    includedInFree: false,
    includedInPro: true,
    envKey: 'COMPOSIO_API_KEY',
    status: 'active',
    docsUrl: 'https://docs.composio.dev',
    emoji: '🔗',
  },

  // ── Comms ────────────────────────────────────────────────
  {
    id: 'twilio',
    name: 'Twilio',
    provider: 'Twilio',
    category: 'comms',
    description: 'SMS and voice calls. Programmable communications.',
    costModel: '$0.0085/SMS, $0.013/min call',
    costPerUnit: 0.0085,
    unit: 'SMS',
    includedInFree: false,
    includedInPro: true,
    envKey: 'TWILIO_ACCOUNT_SID',
    status: 'active',
    docsUrl: 'https://www.twilio.com/docs',
    emoji: '📱',
  },
  {
    id: 'retell',
    name: 'Retell AI',
    provider: 'Retell',
    category: 'comms',
    description: 'AI phone calls. Build conversational voice agents.',
    costModel: '$0.07/min',
    costPerUnit: 0.07,
    unit: 'minute',
    includedInFree: false,
    includedInPro: true,
    envKey: 'RETELL_API_KEY',
    status: 'active',
    docsUrl: 'https://docs.retellai.com',
    emoji: '📞',
  },
  {
    id: 'telegram',
    name: 'Telegram Bot',
    provider: 'Telegram',
    category: 'comms',
    description: 'Bot messaging. Send/receive messages, manage channels.',
    costModel: 'Free',
    costPerUnit: 0,
    unit: 'message',
    includedInFree: true,
    includedInPro: true,
    envKey: 'TELEGRAM_BOT_TOKEN',
    status: 'active',
    docsUrl: 'https://core.telegram.org/bots/api',
    emoji: '✈️',
  },

  // ── Travel ───────────────────────────────────────────────
  {
    id: 'duffel',
    name: 'Duffel',
    provider: 'Duffel',
    category: 'travel',
    description: 'Flight search and booking. Live airline inventory, real tickets.',
    costModel: 'Commission-based',
    costPerUnit: 0,
    unit: 'booking',
    includedInFree: false,
    includedInPro: true,
    envKey: 'DUFFEL_API_KEY',
    status: 'active',
    docsUrl: 'https://duffel.com/docs',
    emoji: '✈️',
  },

  // ── Social ───────────────────────────────────────────────
  {
    id: 'twitter',
    name: 'Twitter / X',
    provider: 'X Corp',
    category: 'social',
    description: 'Post tweets, read timelines, manage social presence.',
    costModel: 'Included (Basic tier)',
    costPerUnit: 0,
    unit: 'tweet',
    includedInFree: false,
    includedInPro: true,
    envKey: 'TWITTER_API_KEY',
    status: 'active',
    docsUrl: 'https://developer.x.com/docs',
    emoji: '🐦',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    provider: 'Microsoft',
    category: 'social',
    description: 'OAuth integration. Profile data, connections.',
    costModel: 'Included',
    costPerUnit: 0,
    unit: 'request',
    includedInFree: false,
    includedInPro: true,
    envKey: 'LINKEDIN_CLIENT_ID',
    status: 'active',
    docsUrl: 'https://learn.microsoft.com/linkedin/',
    emoji: '💼',
  },

  // ── Infra ────────────────────────────────────────────────
  {
    id: 'github',
    name: 'GitHub',
    provider: 'GitHub',
    category: 'infra',
    description: 'Repository management. Code hosting, CI/CD, issues.',
    costModel: 'Free',
    costPerUnit: 0,
    unit: 'request',
    includedInFree: true,
    includedInPro: true,
    envKey: 'GITHUB_PAT',
    status: 'active',
    docsUrl: 'https://docs.github.com',
    emoji: '🐙',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    provider: 'Cloudflare',
    category: 'infra',
    description: 'DNS, tunnels, CDN. Zero-trust access, DDoS protection.',
    costModel: 'Free tier',
    costPerUnit: 0,
    unit: 'request',
    includedInFree: true,
    includedInPro: true,
    envKey: 'CLOUDFLARE_API_TOKEN',
    status: 'active',
    docsUrl: 'https://developers.cloudflare.com',
    emoji: '☁️',
  },
  {
    id: 'railway',
    name: 'Railway',
    provider: 'Railway',
    category: 'infra',
    description: 'Cloud hosting. Deploy apps with zero config.',
    costModel: 'Pay-per-use',
    costPerUnit: 0,
    unit: 'GB-hour',
    includedInFree: false,
    includedInPro: true,
    envKey: 'RAILWAY_TOKEN',
    status: 'active',
    docsUrl: 'https://docs.railway.app',
    emoji: '🚂',
  },

  // ── Media ────────────────────────────────────────────────
  {
    id: 'immich',
    name: 'Immich',
    provider: 'Self-hosted',
    category: 'media',
    description: 'Photo management. Self-hosted Google Photos alternative.',
    costModel: 'Free (self-hosted)',
    costPerUnit: 0,
    unit: 'photo',
    includedInFree: true,
    includedInPro: true,
    envKey: 'IMMICH_API_KEY',
    status: 'active',
    docsUrl: 'https://immich.app/docs',
    emoji: '📸',
  },
]

export const API_CATEGORIES: Record<string, { label: string; emoji: string }> = {
  ai: { label: 'AI & LLM', emoji: '🧠' },
  search: { label: 'Search & Enrichment', emoji: '🔍' },
  data: { label: 'Data & CRM', emoji: '🗄️' },
  comms: { label: 'Communications', emoji: '📱' },
  travel: { label: 'Travel', emoji: '✈️' },
  social: { label: 'Social', emoji: '🐦' },
  infra: { label: 'Infrastructure', emoji: '⚙️' },
  media: { label: 'Media', emoji: '📸' },
}

/** Group APIs by category */
export function getApisByCategory(): Record<string, ApiService[]> {
  const grouped: Record<string, ApiService[]> = {}
  for (const api of API_REGISTRY) {
    if (!grouped[api.category]) grouped[api.category] = []
    grouped[api.category].push(api)
  }
  return grouped
}

/** Count active APIs */
export function getActiveApiCount(): number {
  return API_REGISTRY.filter(a => a.status === 'active').length
}

/** Count pro-only APIs */
export function getProApiCount(): number {
  return API_REGISTRY.filter(a => a.includedInPro && !a.includedInFree).length
}
